version: '3'

services:
#   nginx:
#     container_name: nginx_con
#     image: nginx_img
#     build:
#       context:
#         ./requirements/nginx/
#     ports:
#       - "443:443"
#     restart: always
  # mariadb:
  #   container_name: mariadb_con
  #   image: mariadb_img
  #   build:
  #     context:
  #       ./requirements/mariadb/
  #   ports:
  #     - "3306:3306"
  #   restart: always
  #   volumes:
  #     - wp_database:/var/run/mysqld
  #   environment:
  #     MYSQL_USER: mliew
  #     MYSQL_PASSWORD: mliew123
  #     MYSQL_ROOT_PASSWORD: root123
  #     MYSQL_DATABASE: mydatabase
  wordpress:
    container_name: wordpress_con
    image: wordpress_img
    build:
      context:
        ./requirements/wordpress/
    ports:
      - "9000:9000"
    restart: always

volumes:
  wp_database:
  # wp_files:

