version: '3'

services:
  nginx:
    container_name: nginx_con
    image: nginx_img
    build:
      context:
        ./requirements/nginx/
    networks:
      - inception
    ports:
      - "443:443"
    restart: always
    env_file:
      - .env

  mariadb:
    container_name: mariadb_con
    image: mariadb_img
    build:
      context:
        ./requirements/mariadb/
    networks:
      - inception
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - wp_database:/var/lib/mysql
    env_file:
      - .env

  wordpress:
    container_name: wordpress_con
    image: wordpress_img
    build:
      context:
        ./requirements/wordpress/
    networks:
      - inception
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - wp_files:/var/www/html
    env_file:
      - .env

volumes:
  wp_database:
  wp_files:

networks:
  inception: