version: '3'

services:
  nginx:
    container_name: nginx_con
    image: nginx_img
    build: ./requirements/nginx/
    networks:
      - inception
    ports:
      - "443:443"
    restart: always
    volumes:
      - webfiles:/var/www/html
    env_file:
      - .env

  wordpress:
    container_name: wordpress_con
    image: wordpress_img
    build: ./requirements/wordpress/
    networks:
      - inception
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - webfiles:/var/www/html
    env_file:
      - .env
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb_con
    image: mariadb_img
    build: ./requirements/mariadb/
    networks:
      - inception
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - database:/var/lib/mysql
    env_file:
      - .env

volumes:
  database:
  webfiles:

networks:
  inception:
    driver: bridge